CREATE TABLE IF NOT EXISTS user_tools (
    user_id VARCHAR(255) PRIMARY KEY,
    tools JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 